"""add_rule_id_column_to_transaction

Revision ID: 15e1ed89ff15
Revises: ac8887c5c02b
Create Date: 2025-04-14 23:56:28.601310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e1ed89ff15'
down_revision = 'ac8887c5c02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'rule', ['rule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rule_id')

    # ### end Alembic commands ###
