"""add transaction_hash column

Revision ID: ac8887c5c02b
Revises: cb7555c9aeed
Create Date: 2025-04-14 21:07:21.465694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8887c5c02b'
down_revision = 'cb7555c9aeed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_hash', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_bank_transaction_transaction_hash'), ['transaction_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transaction_transaction_hash'))
        batch_op.drop_column('transaction_hash')

    # ### end Alembic commands ###
